# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iris.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\niris.proto\x12\x02ml\"j\n\x12IrisPredictRequest\x12\x14\n\x0csepal_length\x18\x01 \x01(\x01\x12\x13\n\x0bsepal_width\x18\x02 \x01(\x01\x12\x14\n\x0cpetal_length\x18\x03 \x01(\x01\x12\x13\n\x0bpetal_width\x18\x04 \x01(\x01\"#\n\x10IrisPredictReply\x12\x0f\n\x07species\x18\x01 \x01(\x05\x32N\n\rIrisPredictor\x12=\n\x0bPredictIris\x12\x16.ml.IrisPredictRequest\x1a\x14.ml.IrisPredictReply\"\x00\x42(\n\x13io.grpc.examples.mlB\tIrisProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iris_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023io.grpc.examples.mlB\tIrisProtoP\001\242\002\003HLW'
  _IRISPREDICTREQUEST._serialized_start=18
  _IRISPREDICTREQUEST._serialized_end=124
  _IRISPREDICTREPLY._serialized_start=126
  _IRISPREDICTREPLY._serialized_end=161
  _IRISPREDICTOR._serialized_start=163
  _IRISPREDICTOR._serialized_end=241
# @@protoc_insertion_point(module_scope)
